### ISSUE TITLE
About consistency loss

### ISSUE THREAD

**Issue by jimmy133719** [turpaultn/DCASE2019_task4#10]
Hi,
I'm confused about the comments in main.py line129, 139. They mention that the consistency loss only considers weak and unlabeled data. However, I can't figure out which code excludes strong data consistency. Besides, I find that the reference paper also takes strong data into consideration when computing consistency loss. There is another question I'm not sure. Is unlabeled data been used when training student model? Thanks!

**Comment by turpaultn** [comment]
Hi, 
Sorry for the late answer.
The comment is actually wrong.
It takes the consistency between all the weak predictions, and about all the strong predictions (so using weak, unlabeled and strong data in all cases).
It is a very simple way of doing it, but probably not very accurate to do it like this.
For personal experiences, I use the masks to use or not the consistency between only parts of weak predictions and strong predictions (for example only use consistency for unlabeled data).

Unlabeled data is always used to train the student model, but only used in the consistency loss because we do not have the labels for them (that's why we use "weak mask" and "strong mask").
